# Course Logistics {.unnumbered}

## Learning Objectives {.unnumbered}

By the end of this course, you should:

-   be familiar with **key concepts and methods** in applied data science for acquiring and managing data, conducting exploratory data analyses, testing statistical hypotheses, building models to classify and make predictions about data, and evaluating model performance;
-   have a facility with **modern tools for data analysis**, (e.g., the ***R*** programming environment, version control systems, the Unix command line, web APIs) and be able to apply "best practices" in data science;
-   know how to **interact with both local and remote data sources** to store, query, process, and analyze data presented a variety of common formats (e.g., delimited text files, structured text files, various database systems);
-   be comfortable **writing simple computer programs/scripts** for data management, statistical analysis, visualization, and more specialized applications;
-   know how to design and implement **reproducible data science workflows** that take a project from data acquisition to analysis to presentation and be able to organize your work using a version control system;
-   and be able to apply all of these tools to **questions of interest in the natural and social sciences**.

## Prerequisites {.unnumbered}

At least one semester of introductory statistics is recommended. Prior programming experience is not expected, but would be helpful!