# Exercise 02 {.unnumbered}

# Practice Reproducible Research Workflows {.unnumbered}

## Learning Objectives {.unnumbered}

-   Integrating an ***RStudio*** project, a local ***git*** repository, and a **GitHub** remote repository

## Version 1: Beginning with a remote repo {.unnumbered}

Follow the instructions outlined as **Method 1** in [**Module 6**](#module-06) to do the following:

#### Step 1 {.unnumbered}

- Set up a new ***GitHub*** repo in your ***GitHub*** workspace named "exercise-02".

#### Step 2 {.unnumbered}

- Add me as a collaborator on the repo (my ***GitHub*** username is “difiore”).

#### Step 3 {.unnumbered}

- Clone your repo to your local computer.

#### Step 4 {.unnumbered}

- Create an **RMarkdown** document locally with notes you take in class this week - maybe call it "Notes.Rmd"? - including at least some expository text written in **Markdown** and at least one ***R*** code block.

#### Step 5 {.unnumbered}

- Use {knitr} to `knit()` your **RMardown** document to HTML.

#### Step 6 {.unnumbered}

- Stage (or "add") and "commit" your changes to the repo locally and then "push" those up to ***GitHub***.

#### Step 7 {.unnumbered}

- Visit your repo on ***GitHub*** to confirm that you have done the above steps successfully.

#### Step 8 {.unnumbered}

- Submit the URL for your repo in **Canvas**

## Version 2: Beginning with a local repo {.unnumbered}

This is an alternative workflow that I have found works well. It is described in [**Module 6**](#module-06) as "Option 3" under **Connecting a Local Repo to ***GitHub*** **.

#### Step 1 {.unnumbered}

- From within ***RStudio***, create a new project in a brand new directory of your choosing.

> **NOTE** Be sure to check the box marked "Create a git repository" pressing the "Create Project" button.

#### Step 2 {.unnumbered}

- Configure a ***GitHub*** Personal Access Token (PAT) and add it to your “.Renviron” file as described [**Module 6**](#module-06) using the {usethis} package.

#### Step 3 {.unnumbered}

- Open your project and run `usethis::use_github(protocol="https")` from the ***R*** console within your project's working directory.

#### Step 4 {.unnumbered}

- Answer the question about whether the suggested name for the remote repository is adequate and hit enter.

This will create a new remote repository on ***GitHub***, add it as a `remote origin/main`, and open the ***GitHub*** page for the repository in your browser. Switch back to ***RStudio*** and continue with Steps 4 to 8 from above.
