<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.548">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Applied Data Analysis - 24&nbsp; Mixed Effects or Multilevel Modeling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./27-python-from-R.html" rel="next">
<link href="./23-module.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="css/style.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-module.html">Part II - Statistics and Inference</a></li><li class="breadcrumb-item"><a href="./24-module.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Mixed Effects or Multilevel Modeling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/statistics-hand.svg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Data Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Preliminaries</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-logistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Logistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-course-schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-typography-and-formatting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Typography and Formatting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-programming-style-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programming Style Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resources</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Part I - Using <strong><em>R</em></strong> and <strong><em>RStudio</em></strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with <strong><em>R</em></strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started with <strong><em>RStudio</em></strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Extending the Functionality of <strong><em>R</em></strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Fundamentals of the <strong><em>R</em></strong> Language</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basics of Version Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reproducible Research</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Additional Data Structures in <strong><em>R</em></strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Getting Data into <strong><em>R</em></strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Functions and Flow Control</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Part II - Statistics and Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Central Tendency and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Classical Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Using Permutation Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Error, Power, and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Linear Modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Elements of Regression Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multiple Regression and ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Model Selection in Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-module.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-module.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Mixed Effects or Multilevel Modeling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Part III - Miscellany</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-python-from-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Using <strong><em>Python</em></strong> from <strong><em>R</em></strong></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Exercises</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 01</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 02</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 03</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 04</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-04-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 04 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 05</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-05-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 05 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 07</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-07-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 07 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 08</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 09</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-09-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 09 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-10-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 10 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-11-solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 11 Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 12</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-analysis-replication-assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Analysis Replication</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">References</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">List of Packages Used</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives"><span class="header-section-number">24.1</span> Objectives</a></li>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link" data-scroll-target="#preliminaries"><span class="header-section-number">24.2</span> Preliminaries</a></li>
  <li><a href="#overview-of-mixed-models" id="toc-overview-of-mixed-models" class="nav-link" data-scroll-target="#overview-of-mixed-models"><span class="header-section-number">24.3</span> Overview of “Mixed” Models</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">EXAMPLE:</a></li>
  <li><a href="#challenge" id="toc-challenge" class="nav-link" data-scroll-target="#challenge">CHALLENGE</a></li>
  </ul></li>
  <li><a href="#random-intercept-models" id="toc-random-intercept-models" class="nav-link" data-scroll-target="#random-intercept-models"><span class="header-section-number">24.4</span> Random Intercept Models</a>
  <ul class="collapse">
  <li><a href="#inference-using-lrts" id="toc-inference-using-lrts" class="nav-link" data-scroll-target="#inference-using-lrts">Inference using LRTs</a></li>
  <li><a href="#challenge-1" id="toc-challenge-1" class="nav-link" data-scroll-target="#challenge-1">CHALLENGE</a></li>
  <li><a href="#challenge-2" id="toc-challenge-2" class="nav-link" data-scroll-target="#challenge-2">CHALLENGE</a></li>
  </ul></li>
  <li><a href="#random-slope-models" id="toc-random-slope-models" class="nav-link" data-scroll-target="#random-slope-models"><span class="header-section-number">24.5</span> Random Slope Models</a>
  <ul class="collapse">
  <li><a href="#inference-using-lrts-1" id="toc-inference-using-lrts-1" class="nav-link" data-scroll-target="#inference-using-lrts-1">Inference using LRTs</a></li>
  <li><a href="#inference-using-aic" id="toc-inference-using-aic" class="nav-link" data-scroll-target="#inference-using-aic">Inference using AIC</a></li>
  <li><a href="#other-methods-for-assessing-fit" id="toc-other-methods-for-assessing-fit" class="nav-link" data-scroll-target="#other-methods-for-assessing-fit">Other Methods for Assessing Fit</a></li>
  <li><a href="#challenge-3" id="toc-challenge-3" class="nav-link" data-scroll-target="#challenge-3">CHALLENGE</a></li>
  </ul></li>
  <li><a href="#generalized-lmms" id="toc-generalized-lmms" class="nav-link" data-scroll-target="#generalized-lmms"><span class="header-section-number">24.6</span> Generalized LMMs</a>
  <ul class="collapse">
  <li><a href="#challenge-4" id="toc-challenge-4" class="nav-link" data-scroll-target="#challenge-4">CHALLENGE</a></li>
  </ul></li>
  <li><a href="#concept-review" id="toc-concept-review" class="nav-link" data-scroll-target="#concept-review">Concept Review</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-module.html">Part II - Statistics and Inference</a></li><li class="breadcrumb-item"><a href="./24-module.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Mixed Effects or Multilevel Modeling</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="module-24" class="quarto-section-identifier"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Mixed Effects or Multilevel Modeling</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="objectives" class="level2" data-number="24.1">
<h2 data-number="24.1" class="anchored" data-anchor-id="objectives"><span class="header-section-number">24.1</span> Objectives</h2>
<blockquote class="blockquote">
<p>In this module, we extend our discussion of regression modeling even further to include “mixed effects” or “multilevel” models.</p>
</blockquote>
</section>
<section id="preliminaries" class="level2" data-number="24.2">
<h2 data-number="24.2" class="anchored" data-anchor-id="preliminaries"><span class="header-section-number">24.2</span> Preliminaries</h2>
<ul>
<li>Install and load this package in <strong><em>R</em></strong>: <a href="https://cran.r-project.org/web/packages/lme4/lme4.pdf">{lme4}</a></li>
<li>Load {tidyverse}</li>
</ul>
</section>
<section id="overview-of-mixed-models" class="level2" data-number="24.3">
<h2 data-number="24.3" class="anchored" data-anchor-id="overview-of-mixed-models"><span class="header-section-number">24.3</span> Overview of “Mixed” Models</h2>
<p>A final extension of linear regression modeling that we will talk about is so-called “multilevel” or “mixed effects” modeling. This is a very complex topic, and we will only scratch the surface!</p>
<p>In a (general or generalized) linear mixed model, we have a reponse variable, <span class="math inline">\(Y\)</span>, and observations that fall into different factor categories each with some set of levels (e.g., “sex” with levels “male” and “female”), and we are interested in the effects of the various factors <strong>and</strong> factor levels on the response variable. Generically, if <span class="math inline">\(\mu\)</span> = a population mean response and <span class="math inline">\(\mu_A\)</span> = mean response for observations belonging to factor level A, then the effect of A is given by <span class="math inline">\(\mu\)</span> - <span class="math inline">\(\mu_A\)</span>. We have already dealt with factors and factor levels in our linear regression models when we looked at categorical predictors (e.g., <em>sex</em>, <em>rank category</em>) in our discussions of ANOVA and ANCOVA.</p>
<p>We can conceptualize these factor effects as being either <em>fixed</em> or <em>random</em>. <em>Fixed</em> factors are those that reflect all levels of interest in our study, while <em>random</em> effects are those that represent only a sample of the levels of interest. For example, if we include <strong>sex</strong> as a factor in a model with the factor levels “male” and “female”, this (typically) will cover the entire gamut of levels of interest our study, thus we would consider <strong>sex</strong> a fixed factor. When we were doing ANOVA and ANCOVA analyses previously, we were implicitly looking at the effects of such fixed factors.</p>
<p>However, if our observational data were to consist of repeated observations of the same sampling unit, e.g., measurements taken on the same set of individuals on different dates, <strong>individual ID</strong> would be considered a random factor because it is unlikely that we will have collected data from all possible “levels of interest”, i.e., from all possible individual subjects. We have not yet dealt with such random factors as an additional source of variance in our modeling.</p>
<p>So-called <strong>mixed models</strong>, then, are those that include BOTH fixed and random effects. Including random effects in addition to fixed effects in our models has several ramifications:</p>
<ul>
<li>Using random effects broadens the scope of inference. That is, we can use statistical methods to infer something about the population from which the levels of the random factor have been drawn.</li>
<li>Using random effects naturally incorporates dependence in the model and helps us account for pseudoreplication in our dataset. Observations that share the same level of the random effects are explicitly modeled as being correlated. This makes mixed effect modeling very useful for dealing with time series data, spatially correlated data, or situations where we have repeated observations/measures from the same subjects or sampling unit.</li>
<li>Using random factors often gives more accurate parameter estimates.</li>
<li>Incorporating random factors, however, does require the use of more sophisticated estimation and fitting methods.</li>
</ul>
<p>Not surprisingly, there several different varieties of mixed modeling approaches, which are supported in a variety of different packages in <strong><em>R</em></strong>:</p>
<ul>
<li>Standard or general <strong>Linear Mixed Models (LMM)</strong>, analogous to standard or general linear regression - used when we are dealing with normally distributed variables and error structures.</li>
<li><strong>Generalized Linear Mixed Models (GLMM)</strong>, analogous to generalized linear regresseion - used when we are dealing with various other variable types and error structure (e.g., binary, proportion, or count data).</li>
<li><strong>Nonlinear Mixed Models (NLMM)</strong>, analogous to nonlinear regression - used if we are dealing with situations where our response variable is best modeled by a nonlinear combination of predictor variables.</li>
</ul>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> We have not talked at all in this course about general or generalized NONLINEAR modeling, but it is worth knowing that such approaches are also possible. NONLINEAR modeling is where our regression equation is a <strong>nonlinear</strong> function of the model parameters.</p>
</blockquote>
<p>We will explore “mixed effects” modeling using an example based on this <a href="http://www.bodowinter.com/tutorial/bw_LME_tutorial2.pdf">excellent tutorial</a>.</p>
<section id="example" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="example">EXAMPLE:</h3>
<p>Suppose we have measured the amount of grooming received by female chimpanzees when they are either in their periovulatory period (i.e., the window of 2-3 days around the likely time of ovulation) or duing other portions of their reproductive cycle. We collected data on the <strong>duration of grooming bouts received</strong> and scored a female’s <strong>reproductive condition</strong> at the time as a categorical factor with two levels: “POP” versus “NONPOP”. On top of that, we also recorded data on female parity at the time of the grooming bout, i.e., whether the female had given birth previously (was “parous”, or “P”) or had not yet had an offspring (was “nulliparous”, or “N”).</p>
<p>If we are interested in how reproductive condition and parity influence how much grooming a female receives, our simple regression model would look like this:</p>
<p><span class="math display">\[grooming\ duration \sim reproductive\ condition + parity + \epsilon\]</span></p>
<p>Also imagine that our study design was such that we took multiple observations per subject. That is, our data set includes records of multiple grooming bouts received by each subject. This situation violates the assumption of independence of observations that we make for standard linear regression: multiple responses/measures from the same subject cannot be regarded as independent from each other.</p>
<p>Using a mixed effects model, we can deal with this situation by adding <strong>subject ID</strong> as a random effect in our model. Doing so allows us to address the nonindependence issue by estimating a different set of parameters for each level of the factor “subject”. We can either estimate a different <em>intercept</em> for each subject (which would correspond to each female having a different “baseline” level of grooming received) or estimate a different <em>intercept</em> <strong>and</strong> <em>slope</em> (where individual subjects are presumed to differ both in the baseline level of grooming received and the strength of the relationship between grooming duration, on the one hand, and reproductive condition and parity, on the other). Our mixed effects model estimates these individual level parameters in addition to the main effects of each variable.</p>
<p>This is why a “mixed effects” model is called a <strong>mixed</strong> model. The models that we have considered so far have been <strong>fixed effects only</strong> models and included only one or more “fixed” predictor variables and a general error term. We essentially divided the world into things that we somehow understand or that are systematic (the fixed effects, or the explanatory variables) and things that we could not control for or do not understand (the general error, or <span class="math inline">\(\epsilon\)</span>). These fixed effects models did not examine possible structure <em>within</em> the error term.</p>
<p>In a mixed model, by contrast, we add one or more random effects to our fixed effects that may explain a portion of the variance in our error term.</p>
<p>Let’s explore these idea using some actual data. First, load in the dataset “chimpgrooming.csv” and do some exploratory data analysis:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/chimpgrooming.csv"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Rows: 84 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: ","
## chr (4): subject, parity, season, reprocondition
## dbl (1): duration
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 5
##   subject parity season reprocondition duration
##   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;             &lt;dbl&gt;
## 1 Nina    P      WS     NONPOP             214.
## 2 Nina    P      WS     POP                206.
## 3 Nina    P      WS     NONPOP             294.
## 4 Nina    P      WS     POP                269.
## 5 Nina    P      WS     NONPOP             205.
## 6 Nina    P      WS     POP                287.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##    subject             parity             season          reprocondition    
##  Length:84          Length:84          Length:84          Length:84         
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##     duration     
##  Min.   : 86.34  
##  1st Qu.:132.36  
##  Median :205.41  
##  Mean   :197.81  
##  3rd Qu.:252.27  
##  Max.   :316.23</code></pre>
</div>
</div>
</section>
<section id="challenge" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="challenge">CHALLENGE</h3>
<p>Plot grooming received duration in relation to subject ID…</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> subject, <span class="at">y =</span> duration)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"subject"</span>) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now plot grooming received in relation to reproductive condition…</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now plot grooming received in relation to reproductive condition <em>and</em> parity…</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration, <span class="at">fill =</span> <span class="fu">factor</span>(parity))) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"parity"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> parity, <span class="at">y =</span> duration, <span class="at">fill =</span> <span class="fu">factor</span>(reprocondition))) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"parity"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"repro</span><span class="sc">\n</span><span class="st">condition"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From these plots, we can see lots of [a] individual variation in how much grooming is received, [b] variation in response to reproductive condition, [c] limited variation due to parity, and [d] variation in response to this combination of fixed effects.</p>
<p>Finally, plot grooming received into relation to both a fixed effect (reprocondition) and a random effect (subject)…</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration, <span class="at">fill =</span> <span class="fu">factor</span>(subject))) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"subject"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> subject, <span class="at">y =</span> duration, <span class="at">fill =</span> <span class="fu">factor</span>(reprocondition))) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"subject"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"repro</span><span class="sc">\n</span><span class="st">condition"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="24-module_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What patterns do you see? There is, again, lots of apparent variation!</p>
</section>
</section>
<section id="random-intercept-models" class="level2" data-number="24.4">
<h2 data-number="24.4" class="anchored" data-anchor-id="random-intercept-models"><span class="header-section-number">24.4</span> Random Intercept Models</h2>
<p>We will now perform an initial mixed effects analysis where we look at how reproductive condition and parity (as fixed effects) affect grooming duration, where we include individual subject ID as a random effect.</p>
<p>Here is a first mixed effects model that we will fit, using one extension of formula notation that is commonly used in <strong><em>R</em></strong>.</p>
<p><span class="math display">\[grooming\ duration \sim reproductive\ condition + parity + (1|subject) + \epsilon\]</span></p>
<p>Here, the 1 refers to the fact that we want to estimate an <em>intercept</em> and the pipe “|” operator following the “1” signifies that we want to estimate a <em>different intercept for each subject</em>. Note that this generic formula still contains a general error term, <span class="math inline">\(\epsilon\)</span>, to highlight that there will still be unexplained “error” variance after accounting for both fixed and random effects in the model.</p>
<p>We can think of this formula as saying that we expect our dataset to include multiple observations of the response variable per subject, and these responses will depend, in part, on each subject’s baseline level. This effectively accounts the nonindependence that stems from having multiple responses by the same subject.</p>
<p>The {lme4} package in <strong>R</strong> is commonly used for mixed effects modeling, and the function <code>lmer()</code> is the mixed model equivalent of the function <code>lm()</code>. In the formula syntax for mixed effects models using the {lme4} package, fixed effects are included without parentheses while random effects are included in parentheses (the error, <span class="math inline">\(\epsilon\)</span>, is understood and is not included explicitly).</p>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> We could also use the package {nlme} for mixed effects modeling (which requires a slightly different formula syntax than that used here). That same package also allows us to do <strong>nonlinear</strong> mixed effects modeling, which we will not be talking about. It is important to note that {lme4} uses, by default, a slightly different parameter estimation algorithm than {nlme}. Unless otherwise specified, {lme4} uses “restricted maximum likelihood” (REML) rather than ordinary maximum likelihood estimation, which is what is used in {nlme}. In practice, these give very similar results. We will see below that when we want to compare different models using {lme4}, we will need to tell {lme4} to use ordinary maximum likelihood.</p>
</blockquote>
<p>The code block below implements this first “mixed effects” model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lme <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Linear mixed model fit by REML ['lmerMod']
## Formula: duration ~ reprocondition + parity + (1 | subject)
##    Data: d
## 
## REML criterion at convergence: 796.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.2611 -0.5349 -0.1890  0.3918  3.1994 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 611.9    24.74   
##  Residual             847.3    29.11   
## Number of obs: 84, groups:  subject, 6
## 
## Fixed effects:
##                   Estimate Std. Error t value
## (Intercept)        132.841     15.305   8.680
## reproconditionPOP   20.293      6.352   3.195
## parityP            109.650     21.173   5.179
## 
## Correlation of Fixed Effects:
##             (Intr) rprPOP
## rprcndtnPOP -0.208       
## parityP     -0.692  0.000</code></pre>
</div>
</div>
<p>Let’s focus on the output for the random effects first. Have a look at the column standard deviation. The entry for <em>subject</em> shows us how much variability in grooming duration (apart from that explained by the fixed effects) is due to subject ID. The entry for <em>Residual</em> summarizes the remaining variability in grooming duration that is not due to <em>subject</em> or to our fixed effects. This is our <span class="math inline">\(\epsilon\)</span>, the “random” deviations from the predicted values that are not due to either subject or our fixed effects.</p>
<p>The fixed effects output mirrors the coefficient tables that we have seen previously in our linear models that have focused only on fixed effects. The coefficient “reproconditionPOP” is the <span class="math inline">\(\beta\)</span> coefficient (slope) for the categorical effect of reproductive condition. The positive sign for the coefficient means that grooming duration is GREATER by 20.293 units for POP than for NONPOP females. Then, there’s a standard error associated with this slope, and a t value, which is simply the estimate divided by the standard error.</p>
<p>The coefficient “parityP” is the <span class="math inline">\(\beta\)</span> coefficient for the categorical effect of parity. The grooming duration associated with being parous versus nulliparous is GREATER by 109.65 units.</p>
<p>The INTERCEPT in this case is the grooming duration associated with being an average, nulliparous, NONPOP female. Like the <code>lm()</code> function, the <code>lmer()</code> took whatever factor level came first in the alphabet to be the reference level for each fixed effect variable.</p>
<p>Let’s also look at the coefficients coming out of the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(lme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $subject
##       (Intercept) reproconditionPOP parityP
## Luna    142.76558          20.29286  109.65
## Maya    137.37902          20.29286  109.65
## Nina    118.37755          20.29286  109.65
## Nipa    160.80050          20.29286  109.65
## Sofia    99.80117          20.29286  109.65
## Vita    137.92047          20.29286  109.65
## 
## attr(,"class")
## [1] "coef.mer"</code></pre>
</div>
</div>
<p>We can see the separate intercepts, or “baseline” level of grooming received, associated with each female when they are (presumably) nulliparous and in a NONPOP reproductive condition.</p>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> Not all females are, necessarily, ever seen in a particular parity or reproductive condition!</p>
</blockquote>
<section id="inference-using-lrts" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="inference-using-lrts">Inference using LRTs</h3>
<p>In mixed effects models, it is not as straightforward as it is for standard linear models to determine p values associated with either overall models or individual coefficients. However, using <strong>likelihood ratio tests</strong>, which we previously used for comparing among generalized linear models, is one common approach. Likelihood is the probability of seeing the data we have actually collected <em>given</em> a particular model. The logic of the likelihood ratio test is to compare the likelihood of two models with each other, i.e., a model that includes the factor that we are interested in versus a reduced, nested model with that factor excluded.</p>
<p>So… if we are interested in the effect of <strong>reproductive condition</strong> on grooming duration, we could compare a more complex model…</p>
<p><span class="math display">\[grooming\ duration \sim reproductive\ condition + parity + (1|subject) + \epsilon\]</span></p>
<p>to a nested, less complex model…</p>
<p><span class="math display">\[grooming\ duration \sim parity + (1|subject) + \epsilon\]</span></p>
<p>In <strong><em>R</em></strong>, we would do this as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note the additional `REML=` argument</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Linear mixed model fit by maximum likelihood  ['lmerMod']
## Formula: duration ~ reprocondition + parity + (1 | subject)
##    Data: d
## 
##      AIC      BIC   logLik deviance df.resid 
##    825.7    837.9   -407.9    815.7       79 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.2996 -0.5283 -0.1783  0.4032  3.2285 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 388.6    19.71   
##  Residual             836.4    28.92   
## Number of obs: 84, groups:  subject, 6
## 
## Fixed effects:
##                   Estimate Std. Error t value
## (Intercept)        132.841     12.625  10.522
## reproconditionPOP   20.293      6.311   3.215
## parityP            109.650     17.288   6.343
## 
## Correlation of Fixed Effects:
##             (Intr) rprPOP
## rprcndtnPOP -0.250       
## parityP     -0.685  0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Linear mixed model fit by maximum likelihood  ['lmerMod']
## Formula: duration ~ parity + (1 | subject)
##    Data: d
## 
##      AIC      BIC   logLik deviance df.resid 
##    833.4    843.2   -412.7    825.4       80 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4996 -0.6492 -0.1198  0.6594  2.7072 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 380.6    19.51   
##  Residual             947.3    30.78   
## Number of obs: 84, groups:  subject, 6
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   142.99      12.22  11.697
## parityP       109.65      17.29   6.343
## 
## Correlation of Fixed Effects:
##         (Intr)
## parityP -0.707</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> Here, we added the argument <code>REML=FALSE</code> to the <code>lmer()</code> function. This is necessary to do when we want to compare models using the likelihood ratio test. Basically, REML uses a different algorithm to determine likelihood values than ordinary likelihood, and, if we want to use these likelihoods to execute an LRT, we need to use ordinary likelihood. See <a href="http://users.stat.umn.edu/~gary/classes/5303/handouts/REML.pdf">this site</a> for a more complete explanation of this issue.</p>
</blockquote>
<p>We then perform the likelihood ratio test using the <code>anova()</code> function or the <code>lrtest()</code> function from {lmtest}.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Data: d
## Models:
## reduced: duration ~ parity + (1 | subject)
## full: duration ~ reprocondition + parity + (1 | subject)
##         npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)   
## reduced    4 833.43 843.15 -412.72   825.43                        
## full       5 825.72 837.88 -407.86   815.72 9.7089  1   0.001834 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(reduced, full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Likelihood ratio test
## 
## Model 1: duration ~ parity + (1 | subject)
## Model 2: duration ~ reprocondition + parity + (1 | subject)
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)   
## 1   4 -412.72                        
## 2   5 -407.86  1 9.7089   0.001834 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These results tell us that the model containing both <strong>reproductive condition</strong> and <strong>parity</strong> as <em>fixed</em> effects fits the data better than a model lacking <strong>reproductive condition</strong> and containing only <strong>parity</strong> as a <em>fixed</em> effect, while accounting for <strong>subject</strong> as a <em>random</em> effect.</p>
</section>
<section id="challenge-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="challenge-1">CHALLENGE</h3>
<p>Now, compare a model containing <strong>reproductive condition</strong> and <strong>parity</strong> to one containing just <strong>reproductive condition</strong>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>## Data: d
## Models:
## reduced: duration ~ reprocondition + (1 | subject)
## full: duration ~ reprocondition + parity + (1 | subject)
##         npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
## reduced    4 835.97 845.70 -413.99   827.97                         
## full       5 825.72 837.88 -407.86   815.72 12.251  1   0.000465 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on this result, including <strong>parity</strong> as well as <strong>reproductive condition</strong> as fixed effects also significantly improves the fit of our model.</p>
</section>
<section id="challenge-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="challenge-2">CHALLENGE</h3>
<p>Construct a model that includes an interaction of <strong>reproductive condition</strong> and <strong>parity</strong> and compare it to a model without the interaction term. Is the interaction of these two fixed effects significant?</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">*</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>## Data: d
## Models:
## reduced: duration ~ reprocondition + parity + (1 | subject)
## full: duration ~ reprocondition * parity + (1 | subject)
##         npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## reduced    5 825.72 837.88 -407.86   815.72                     
## full       6 826.41 840.99 -407.20   814.41 1.3124  1      0.252</code></pre>
</div>
</div>
<p>In this case, adding the interaction of <strong>reproductive condition</strong> and <strong>parity</strong> does not significantly improve the explanatory power of the model.</p>
</section>
</section>
<section id="random-slope-models" class="level2" data-number="24.5">
<h2 data-number="24.5" class="anchored" data-anchor-id="random-slope-models"><span class="header-section-number">24.5</span> Random Slope Models</h2>
<p>In the exercise above, we included only estimation of a separate INTERCEPT for each female and presumed that the same relationships (SLOPES) between grooming duration and reproductive condition + parity obtained for all females. But we can also allow that relationship to vary from subject to subject. We would indicate this model in formula notation as follows:</p>
<p><span class="math display">\[grooming\ duration \sim reproductive\ condition + parity\ +\]</span> <span class="math display">\[(1 + reproductive\ condition|subject) + (1 + parity|subject) + \epsilon\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lme <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Linear mixed model fit by maximum likelihood  ['lmerMod']
## Formula: duration ~ reprocondition + parity + (1 + reprocondition | subject) +  
##     (1 + parity | subject)
##    Data: d
## 
##      AIC      BIC   logLik deviance df.resid 
##    833.6    857.9   -406.8    813.6       74 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.4514 -0.6093 -0.1559  0.3851  3.2152 
## 
## Random effects:
##  Groups    Name              Variance Std.Dev. Corr 
##  subject   (Intercept)        84.020   9.166        
##            reproconditionPOP   1.469   1.212   -1.00
##  subject.1 (Intercept)       628.419  25.068        
##            parityP           627.945  25.059   -1.00
##  Residual                    835.801  28.910        
## Number of obs: 84, groups:  subject, 6
## 
## Fixed effects:
##                   Estimate Std. Error t value
## (Intercept)        132.530     16.293   8.134
## reproconditionPOP   20.293      6.328   3.207
## parityP            110.272     17.258   6.390
## 
## Correlation of Fixed Effects:
##             (Intr) rprPOP
## rprcndtnPOP -0.211       
## parityP     -0.902  0.000
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help('isSingular')</code></pre>
</div>
</div>
<p>Here, we have changed the random effects, which now look a little more complicated. The notation “(1 + reprocondition | subject)” tells the model to estimate differing baseline levels of grooming duration (the intercept, represented by 1) as well as differing responses to the main factor in question, which is reproductive condition in this case. We do the same for parity.</p>
<p>Looking at the coefficients of the new model, we see the effects. Each female now has a different intercept <strong>and</strong> a different coefficient for the slopes of grooming duration as a function of both reproductive condition and parity.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(lme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $subject
##       (Intercept) reproconditionPOP   parityP
## Luna     144.8594          19.47768 110.25259
## Maya     137.6452          19.95465 110.26271
## Nina     113.0874          21.57830 110.30006
## Nipa     139.1961          19.85212  84.78083
## Sofia    125.3318          20.76876 140.06436
## Vita     135.0590          20.12564 105.97018
## 
## attr(,"class")
## [1] "coef.mer"</code></pre>
</div>
</div>
<section id="inference-using-lrts-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="inference-using-lrts-1">Inference using LRTs</h3>
<p>To then get p values associated with each of the fixed factors, we can use likelihood ratio tests…</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># random factors only</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># full model with both fixed effects</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># model without reproductive condition as a fixed effect</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>minusRC <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> parity <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    parity <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># model without parity as a fixed effect</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>minusP <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co"># p value for reproductive condition as a fixed effect</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(minusRC, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Data: d
## Models:
## minusRC: duration ~ parity + (1 + reprocondition | subject) + (1 + parity | subject)
## full: duration ~ reprocondition + parity + (1 + reprocondition | subject) + (1 + parity | subject)
##         npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)   
## minusRC    9 840.23 862.11 -411.11   822.23                        
## full      10 833.63 857.94 -406.82   813.63 8.5963  1   0.003368 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p value for parity as a fixed effect</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(minusP, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Data: d
## Models:
## minusP: duration ~ reprocondition + (1 + reprocondition | subject) + (1 + parity | subject)
## full: duration ~ reprocondition + parity + (1 + reprocondition | subject) + (1 + parity | subject)
##        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)   
## minusP    9 840.08 861.96 -411.04   822.08                        
## full     10 833.63 857.94 -406.82   813.63 8.4473  1   0.003656 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="inference-using-aic" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="inference-using-aic">Inference using AIC</h3>
<p>For a long time, the appropriateness of our mixed models was assessed as above - i.e., by evaluating the significance of each fixed effect using LRTs. As information theoretic approaches have become more popular, it is increasingly common to assess model fit by comparing the AIC values of different models, acknowledging the caveat that AIC can only tell us about the <em>relative</em> fit of alternative models, but not whether a particular model is a good fit, overall. Recall that AIC values are a way of inverting and scaling model log-likelihoods that penalizes models with greater numbers of parameters.</p>
<p>The <code>aictab()</code> function from {AICcmodavg} neatly prints out tables with AIC, Delta AIC, and log-likelihood values, along with AIC “weights”.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>(aic_table <span class="ot">&lt;-</span> <span class="fu">aictab</span>(<span class="fu">list</span>(full, minusRC, minusP, null), <span class="at">modnames =</span> <span class="fu">c</span>(<span class="st">"full"</span>, <span class="st">"minusRC"</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"minusP"</span>, <span class="st">"null"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Model selection based on AICc:
## 
##          K   AICc Delta_AICc AICcWt Cum.Wt      LL
## full    10 836.65       0.00   0.91   0.91 -406.82
## minusP   9 842.51       5.87   0.05   0.95 -411.04
## minusRC  9 842.66       6.02   0.04   1.00 -411.11
## null     8 851.47      14.82   0.00   1.00 -416.77</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>AICcmodavg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> Here we are printing out AICc values, rather than AIC values. AICc is simply a version of AIC with a correction added for small sample sizes. To print the uncorrected AIC values, which appear in the <code>anova()</code> LRT output, we can add the argument <code>second.ord=TRUE</code> to the <code>aictab()</code> function.</p>
</blockquote>
<p><span class="math display">\[AIC_c = AIC + \frac{2K^2 + 2K}{n-K-1}\]</span></p>
<p>where <span class="math inline">\(K\)</span> is the number of parameters and <span class="math inline">\(n\)</span> is the sample size.</p>
<p>In the table, for each model, <span class="math inline">\(K\)</span> is the number of model parameters, the <span class="math inline">\(Delta\  AICc\)</span> value is the difference between that model’s AICc and the best model’s AICc (again, here, that is the full model), and the <span class="math inline">\(AICc\ weight\)</span> is the relative likelihood of that model. [The weights for a particular set of models sums to 1, with each weight equal to the model’s likelihood divided by the summed likelihoods across all models.]</p>
<p>Where the best model has a very high Akaike weight, e.g., &gt;0.9, it is reasonable to base inferences about the included variables on that single most parsimonious model, but when several models rank highly (e.g., several models have Delta AICc values &lt;2 to 4), it is common to model-average effect sizes for the variables that have the most support across that set of models. That is, “model averaging” means making inferences based on a <strong>set</strong> of candidate models, instead of on a single “best” model.</p>
<p>Here, note that the full model containing both <em>reproductive condition</em> and <em>parity</em> has the highest likelihood (the least negative log-likelihood value) and a much lower AICc than any of the less complex alternative models tested. It also has a very high Akaike weight (0.91).</p>
<blockquote class="blockquote">
<p><strong>NOTE:</strong> When running a number of the above models and/or in doing the likelihood ratio tests, we saw a significant result but we also got either a warning that our null models “failed to converge” or we saw a warning about a “boundary (singular) fit”. Both of these warning are due to having a LOT of parameters we are trying to estimate relative to the number of observations we have. Dealing with lack of convergence in fitting maximum likelihood models is beyond what we can cover here, but I encourage you to explore that on your own!</p>
</blockquote>
</section>
<section id="other-methods-for-assessing-fit" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="other-methods-for-assessing-fit">Other Methods for Assessing Fit</h3>
<p>Using likelihood ratio tests and AIC values for evaluating and expressing how well a particular model fits a dataset both have some critical limitations:</p>
<ul>
<li>While AIC provides an estimate of the <em>relative</em> fit of various models, it does not say anything about the absolute fit</li>
<li>AIC does not address the amount of variance in a response variable explained by a model</li>
<li>AIC is not comparable across datasets, and so fit is not generalizable</li>
</ul>
<p>Nakagawa &amp; Schielzeth (2013) and Nakagawa et al.&nbsp;(2017) have published a simple and effective method for calculating a type of <em>pseudo-</em><span class="math inline">\(R^2\)</span> (or coefficient of determination) value for generalized linear mixed models, and because linear mixed models are a specific type of GLMM, this method can be used with LMMs as well.</p>
<blockquote class="blockquote">
<p>See:</p>
<ul>
<li><p>Nakagawa, S., &amp; Schielzeth, H. (2013). A general and simple method for obtaining R2 from generalized linear mixed-effects models. <em>Methods in Ecology and Evolution</em>, 4, 133–142.</p></li>
<li><p>Nakagawa, S., Johnson, P. C. D., &amp; Schielzeth, H. (2017). The coefficient of determination R2 and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded. <em>Journal of the Royal Society Interface</em>, 14, article 20170213.</p></li>
</ul>
</blockquote>
<p>In these papers, two measures are proposed for characterizing the amount of “variance explained” in for mixed effects models:</p>
<ul>
<li><span class="math inline">\(Marginal\ R2GLMM(m)^2\)</span> is the amount of variance explained on the latent (or link) scale rather than the original scale. We can interpret this as a measure of the variance explained by only the fixed effects.</li>
<li><span class="math inline">\(Conditional\ R2GLMM(c)^2\)</span> is the amount of variance explained by both fixed and random effects, i.e., by the entire model.</li>
</ul>
<p>There is an easy way to calculate these two R2GLMM values in <strong><em>R</em></strong> using the <code>r.squaredGLMM()</code> function in the package {MuMIn}.</p>
</section>
<section id="challenge-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="challenge-3">CHALLENGE</h3>
<p>Compare the full, the two reduced, and the null mixed effects models from our random slope exercise using an information theoretic approach. Is the best model (full) the one that explains the greatest amount of variance in the dataset? In the full model, how much more of the total variance is explained by the random effects than by the fixed effects alone?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>aic_table  <span class="co"># re-print the AIC table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Model selection based on AICc:
## 
##          K   AICc Delta_AICc AICcWt Cum.Wt      LL
## full    10 836.65       0.00   0.91   0.91 -406.82
## minusP   9 842.51       5.87   0.05   0.95 -411.04
## minusRC  9 842.66       6.02   0.04   1.00 -411.11
## null     8 851.47      14.82   0.00   1.00 -416.77</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##            R2m       R2c
## [1,] 0.7221769 0.8102366</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(minusRC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##            R2m    R2c
## [1,] 0.6778132 0.7898</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(minusP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##             R2m       R2c
## [1,] 0.01443171 0.8841458</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(null)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##      R2m       R2c
## [1,]   0 0.8714428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>MuMIn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="generalized-lmms" class="level2" data-number="24.6">
<h2 data-number="24.6" class="anchored" data-anchor-id="generalized-lmms"><span class="header-section-number">24.6</span> Generalized LMMs</h2>
<p>Just as we extended our standard linear modeling approach to include non-normally distributed response variables/error structures, so too can we extend our mixed effects modeling to such situations. This is referred to as <strong>generalized linear mixed modeling, or GLMM</strong>. There are several <strong><em>R</em></strong> packages we can use to do this under either a maximum likelihood (e.g., {lme4}, {glmmML}, the no-longer-maintained {glmmboot}) or Bayesian (e.g., {MCMCglmm}, {glmmTMB}, {brms}) framework. The methods for generating maximum likelihood and Bayesian parameter estimates under GLMMs are more complicated, but conceptually, the process is an extension of what we have talked about already. Below, we explore such a scenario.</p>
<section id="challenge-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="challenge-4">CHALLENGE</h3>
<p>Boden-Parry et al.&nbsp;(2020) studied the effect of food type and abundance on the begging and food sharing behavior of otters in captivity.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Bowden-ParryOtterdata.csv"</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Rows: 180 Columns: 22
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: ","
## chr  (6): zoo, ID, fooddensity, foodtype, agecategory, sex
## dbl (16): trialorder, forcedclaim, unsuccessfulforcedclaim, activebeg, passi...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 22
##   zoo   ID    fooddensity foodtype trialorder forcedclaim unsuccessfulforcedcl…¹
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;                  &lt;dbl&gt;
## 1 T     Feet  medium      trout             7           0                      0
## 2 T     Feet  a_low       trout             8           0                      0
## 3 T     Feet  high        trout             9           0                      0
## 4 T     Feet  medium      crab              1           0                      0
## 5 T     Feet  a_low       crab              2           0                      0
## 6 T     Feet  high        crab              3           0                      0
## # ℹ abbreviated name: ¹​unsuccessfulforcedclaim
## # ℹ 15 more variables: activebeg &lt;dbl&gt;, passivebeg &lt;dbl&gt;, totalbeg &lt;dbl&gt;,
## #   collectnear &lt;dbl&gt;, relaxedclaim &lt;dbl&gt;, foodgiving &lt;dbl&gt;,
## #   totalshareproonly &lt;dbl&gt;, attackfromowner &lt;dbl&gt;, trialduration &lt;dbl&gt;,
## #   agecategory &lt;chr&gt;, sex &lt;chr&gt;, begreceived &lt;dbl&gt;,
## #   ownersharebecauseharassed &lt;dbl&gt;, TotalSharebothharasspro &lt;dbl&gt;,
## #   sharingbybegonly &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmML)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Registered S3 methods overwritten by 'glmmML':
##   method         from 
##   summary.glmmML MuMIn
##   nobs.glmmML    MuMIn</code></pre>
</div>
</div>
<p>Bowden-Parry, M.; Postma, E.; and Boogert, N.J. (2020). Effects of food type and abundance on begging and sharing in Asian small-clawed otters (<em>Aonyx cinereus</em>). <em>PeerJ</em> 8: e10369.</p>
<hr>
</section>
</section>
<section id="concept-review" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="concept-review">Concept Review</h2>
<ul>
<li>“Mixed” modeling extends general and generalized linear modeling to consider cases where we have additional “random” factors that are another source of possible variation in our response variable</li>
<li>The approach allows us to estimate either different intercepts or different slopes <em>and</em> intercepts for each level of the random factor</li>
<li>As in generalized linear modeling, likelihood ratio tests and information criteria approaches can be used to compare the explanatory power of different models</li>
<li>Though we do not address it in this class, regression modeling can be extended further to consider NONLINEAR relationships among predictor variables
<ul>
<li>The <strong><em>R</em></strong> packages {lme4} and {nlme} provide functions for performing for “nonlinear mixed effects modeling”</li>
</ul></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./23-module.html" class="pagination-link  aria-label=" &lt;span="" linear="" models&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./27-python-from-R.html" class="pagination-link" aria-label="<span class='chapter-number'>25</span>&nbsp; <span class='chapter-title'>Using ***Python*** from ***R***</span>">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Using <strong><em>Python</em></strong> from <strong><em>R</em></strong></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb58" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Mixed Effects or Multilevel Modeling {#module-24}</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objectives</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; In this module, we extend our discussion of regression modeling even further to include "mixed effects" or "multilevel" models.</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preliminaries</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Install and load this package in ***R***: <span class="co">[</span><span class="ot">{lme4}</span><span class="co">](https://cran.r-project.org/web/packages/lme4/lme4.pdf)</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Load {tidyverse}</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview of "Mixed" Models</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>A final extension of linear regression modeling that we will talk about is so-called "multilevel" or "mixed effects" modeling. This is a very complex topic, and we will only scratch the surface!</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>In a (general or generalized) linear mixed model, we have a reponse variable, $Y$, and observations that fall into different factor categories each with some set of levels (e.g., "sex" with levels "male" and "female"), and we are interested in the effects of the various factors **and** factor levels on the response variable. Generically, if $\mu$ = a population mean response and $\mu_A$ = mean response for observations belonging to factor level A, then the effect of A is given by $\mu$ - $\mu_A$. We have already dealt with factors and factor levels in our linear regression models when we looked at categorical predictors (e.g., *sex*, *rank category*) in our discussions of ANOVA and ANCOVA.</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>We can conceptualize these factor effects as being either *fixed* or *random*. *Fixed* factors are those that reflect all levels of interest in our study, while *random* effects are those that represent only a sample of the levels of interest. For example, if we include **sex** as a factor in a model with the factor levels "male" and "female", this (typically) will cover the entire gamut of levels of interest our study, thus we would consider **sex** a fixed factor. When we were doing ANOVA and ANCOVA analyses previously, we were implicitly looking at the effects of such fixed factors.</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a>However, if our observational data were to consist of repeated observations of the same sampling unit, e.g., measurements taken on the same set of individuals on different dates, **individual ID** would be considered a random factor because it is unlikely that we will have collected data from all possible "levels of interest", i.e., from all possible individual subjects. We have not yet dealt with such random factors as an additional source of variance in our modeling.</span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a>So-called **mixed models**, then, are those that include BOTH fixed and random effects. Including random effects in addition to fixed effects in our models has several ramifications:</span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-32"><a href="#cb58-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Using random effects broadens the scope of inference. That is, we can use statistical methods to infer something about the population from which the levels of the random factor have been drawn.</span>
<span id="cb58-33"><a href="#cb58-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Using random effects naturally incorporates dependence in the model and helps us account for pseudoreplication in our dataset. Observations that share the same level of the random effects are explicitly modeled as being correlated. This makes mixed effect modeling very useful for dealing with time series data, spatially correlated data, or situations where we have repeated observations/measures from the same subjects or sampling unit.</span>
<span id="cb58-34"><a href="#cb58-34" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Using random factors often gives more accurate parameter estimates.</span>
<span id="cb58-35"><a href="#cb58-35" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Incorporating random factors, however, does require the use of more sophisticated estimation and fitting methods.</span>
<span id="cb58-36"><a href="#cb58-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-37"><a href="#cb58-37" aria-hidden="true" tabindex="-1"></a>Not surprisingly, there several different varieties of mixed modeling approaches, which are supported in a variety of different packages in ***R***:</span>
<span id="cb58-38"><a href="#cb58-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-39"><a href="#cb58-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Standard or general **Linear Mixed Models (LMM)**, analogous to standard or general linear regression - used when we are dealing with normally distributed variables and error structures.</span>
<span id="cb58-40"><a href="#cb58-40" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Generalized Linear Mixed Models (GLMM)**, analogous to generalized linear regresseion - used when we are dealing with various other variable types and error structure (e.g., binary, proportion, or count data).</span>
<span id="cb58-41"><a href="#cb58-41" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Nonlinear Mixed Models (NLMM)**, analogous to nonlinear regression - used if we are dealing with situations where our response variable is best modeled by a nonlinear combination of predictor variables.</span>
<span id="cb58-42"><a href="#cb58-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-43"><a href="#cb58-43" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** We have not talked at all in this course about general or generalized NONLINEAR modeling, but it is worth knowing that such approaches are also possible. NONLINEAR modeling is where our regression equation is a **nonlinear** function of the model parameters.</span></span>
<span id="cb58-44"><a href="#cb58-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-45"><a href="#cb58-45" aria-hidden="true" tabindex="-1"></a>We will explore "mixed effects" modeling using an example based on this <span class="co">[</span><span class="ot">excellent tutorial</span><span class="co">](http://www.bodowinter.com/tutorial/bw_LME_tutorial2.pdf)</span>.</span>
<span id="cb58-46"><a href="#cb58-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-47"><a href="#cb58-47" aria-hidden="true" tabindex="-1"></a><span class="fu">### EXAMPLE: {.unnumbered}</span></span>
<span id="cb58-48"><a href="#cb58-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-49"><a href="#cb58-49" aria-hidden="true" tabindex="-1"></a>Suppose we have measured the amount of grooming received by female chimpanzees when they are either in their periovulatory period (i.e., the window of 2-3 days around the likely time of ovulation) or duing other portions of their reproductive cycle. We collected data on the **duration of grooming bouts received** and scored a female's **reproductive condition** at the time as a categorical factor with two levels: "POP" versus "NONPOP". On top of that, we also recorded data on female parity at the time of the grooming bout, i.e., whether the female had given birth previously (was "parous", or "P") or had not yet had an offspring (was "nulliparous", or "N").</span>
<span id="cb58-50"><a href="#cb58-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-51"><a href="#cb58-51" aria-hidden="true" tabindex="-1"></a>If we are interested in how reproductive condition and parity influence how much grooming a female receives, our simple regression model would look like this:</span>
<span id="cb58-52"><a href="#cb58-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-53"><a href="#cb58-53" aria-hidden="true" tabindex="-1"></a>$$grooming\ duration \sim reproductive\ condition + parity + \epsilon$$</span>
<span id="cb58-54"><a href="#cb58-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-55"><a href="#cb58-55" aria-hidden="true" tabindex="-1"></a>Also imagine that our study design was such that we took multiple observations per subject. That is, our data set includes records of multiple grooming bouts received by each subject. This situation violates the assumption of independence of observations that we make for standard linear regression: multiple responses/measures from the same subject cannot be regarded as independent from each other.</span>
<span id="cb58-56"><a href="#cb58-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-57"><a href="#cb58-57" aria-hidden="true" tabindex="-1"></a>Using a mixed effects model, we can deal with this situation by adding **subject ID** as a random effect in our model. Doing so allows us to address the nonindependence issue by estimating a different set of parameters for each level of the factor "subject". We can either estimate a different *intercept* for each subject (which would correspond to each female having a different "baseline" level of grooming received) or estimate a different *intercept* **and** *slope* (where individual subjects are presumed to differ both in the baseline level of grooming received and the strength of the relationship between grooming duration, on the one hand, and reproductive condition and parity, on the other). Our mixed effects model estimates these individual level parameters in addition to the main effects of each variable.</span>
<span id="cb58-58"><a href="#cb58-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-59"><a href="#cb58-59" aria-hidden="true" tabindex="-1"></a>This is why a "mixed effects" model is called a **mixed** model. The models that we have considered so far have been **fixed effects only** models and included only one or more "fixed" predictor variables and a general error term. We essentially divided the world into things that we somehow understand or that are systematic (the fixed effects, or the explanatory variables) and things that we could not control for or do not understand (the general error, or $\epsilon$). These fixed effects models did not examine possible structure *within* the error term.</span>
<span id="cb58-60"><a href="#cb58-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-61"><a href="#cb58-61" aria-hidden="true" tabindex="-1"></a>In a mixed model, by contrast, we add one or more random effects to our fixed effects that may explain a portion of the variance in our error term.</span>
<span id="cb58-62"><a href="#cb58-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-63"><a href="#cb58-63" aria-hidden="true" tabindex="-1"></a>Let's explore these idea using some actual data. First, load in the dataset "chimpgrooming.csv" and do some exploratory data analysis:</span>
<span id="cb58-64"><a href="#cb58-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-67"><a href="#cb58-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-68"><a href="#cb58-68" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/chimpgrooming.csv"</span></span>
<span id="cb58-69"><a href="#cb58-69" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-70"><a href="#cb58-70" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span>
<span id="cb58-71"><a href="#cb58-71" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span>
<span id="cb58-72"><a href="#cb58-72" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-73"><a href="#cb58-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-74"><a href="#cb58-74" aria-hidden="true" tabindex="-1"></a><span class="fu">### CHALLENGE {.unnumbered}</span></span>
<span id="cb58-75"><a href="#cb58-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-76"><a href="#cb58-76" aria-hidden="true" tabindex="-1"></a>Plot grooming received duration in relation to subject ID...</span>
<span id="cb58-77"><a href="#cb58-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-80"><a href="#cb58-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-81"><a href="#cb58-81" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-82"><a href="#cb58-82" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>d, <span class="fu">aes</span>(<span class="at">x=</span>subject, <span class="at">y=</span>duration)) <span class="sc">+</span></span>
<span id="cb58-83"><a href="#cb58-83" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"subject"</span>) <span class="sc">+</span></span>
<span id="cb58-84"><a href="#cb58-84" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-85"><a href="#cb58-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-86"><a href="#cb58-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-87"><a href="#cb58-87" aria-hidden="true" tabindex="-1"></a>Now plot grooming received in relation to reproductive condition...</span>
<span id="cb58-88"><a href="#cb58-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-91"><a href="#cb58-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-92"><a href="#cb58-92" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-93"><a href="#cb58-93" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration)) <span class="sc">+</span></span>
<span id="cb58-94"><a href="#cb58-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span></span>
<span id="cb58-95"><a href="#cb58-95" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-96"><a href="#cb58-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-97"><a href="#cb58-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-98"><a href="#cb58-98" aria-hidden="true" tabindex="-1"></a>Now plot grooming received in relation to reproductive condition *and* parity...</span>
<span id="cb58-99"><a href="#cb58-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-102"><a href="#cb58-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-103"><a href="#cb58-103" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-104"><a href="#cb58-104" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration,</span>
<span id="cb58-105"><a href="#cb58-105" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill=</span><span class="fu">factor</span>(parity))) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb58-106"><a href="#cb58-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span></span>
<span id="cb58-107"><a href="#cb58-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"parity"</span>) <span class="sc">+</span></span>
<span id="cb58-108"><a href="#cb58-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-109"><a href="#cb58-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-110"><a href="#cb58-110" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb58-111"><a href="#cb58-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-112"><a href="#cb58-112" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> parity, <span class="at">y =</span> duration,</span>
<span id="cb58-113"><a href="#cb58-113" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill=</span><span class="fu">factor</span>(reprocondition))) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb58-114"><a href="#cb58-114" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"parity"</span>) <span class="sc">+</span></span>
<span id="cb58-115"><a href="#cb58-115" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"repro</span><span class="sc">\n</span><span class="st">condition"</span>) <span class="sc">+</span></span>
<span id="cb58-116"><a href="#cb58-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-117"><a href="#cb58-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-118"><a href="#cb58-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-119"><a href="#cb58-119" aria-hidden="true" tabindex="-1"></a>From these plots, we can see lots of <span class="co">[</span><span class="ot">a</span><span class="co">]</span> individual variation in how much grooming is received, <span class="co">[</span><span class="ot">b</span><span class="co">]</span> variation in response to reproductive condition, <span class="co">[</span><span class="ot">c</span><span class="co">]</span> limited variation due to parity, and <span class="co">[</span><span class="ot">d</span><span class="co">]</span> variation in response to this combination of fixed effects.</span>
<span id="cb58-120"><a href="#cb58-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-121"><a href="#cb58-121" aria-hidden="true" tabindex="-1"></a>Finally, plot grooming received into relation to both a fixed effect (reprocondition) and a random effect (subject)...</span>
<span id="cb58-122"><a href="#cb58-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-125"><a href="#cb58-125" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-126"><a href="#cb58-126" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-127"><a href="#cb58-127" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> reprocondition, <span class="at">y =</span> duration,</span>
<span id="cb58-128"><a href="#cb58-128" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="fu">factor</span>(subject))) <span class="sc">+</span></span>
<span id="cb58-129"><a href="#cb58-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb58-130"><a href="#cb58-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"reproductive condition"</span>) <span class="sc">+</span></span>
<span id="cb58-131"><a href="#cb58-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"subject"</span>) <span class="sc">+</span></span>
<span id="cb58-132"><a href="#cb58-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-133"><a href="#cb58-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-134"><a href="#cb58-134" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb58-135"><a href="#cb58-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-136"><a href="#cb58-136" aria-hidden="true" tabindex="-1"></a>(p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d, <span class="fu">aes</span>(<span class="at">x =</span> subject, <span class="at">y =</span> duration,</span>
<span id="cb58-137"><a href="#cb58-137" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="fu">factor</span>(reprocondition))) <span class="sc">+</span></span>
<span id="cb58-138"><a href="#cb58-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb58-139"><a href="#cb58-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"subject"</span>) <span class="sc">+</span></span>
<span id="cb58-140"><a href="#cb58-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"repro</span><span class="sc">\n</span><span class="st">condition"</span>) <span class="sc">+</span></span>
<span id="cb58-141"><a href="#cb58-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)))</span>
<span id="cb58-142"><a href="#cb58-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-143"><a href="#cb58-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-144"><a href="#cb58-144" aria-hidden="true" tabindex="-1"></a>What patterns do you see? There is, again, lots of apparent variation!</span>
<span id="cb58-145"><a href="#cb58-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-146"><a href="#cb58-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## Random Intercept Models</span></span>
<span id="cb58-147"><a href="#cb58-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-148"><a href="#cb58-148" aria-hidden="true" tabindex="-1"></a>We will now perform an initial mixed effects analysis where we look at how reproductive condition and parity (as fixed effects) affect grooming duration, where we include individual subject ID as a random effect.</span>
<span id="cb58-149"><a href="#cb58-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-150"><a href="#cb58-150" aria-hidden="true" tabindex="-1"></a>Here is a first mixed effects model that we will fit, using one extension of formula notation that is commonly used in ***R***.</span>
<span id="cb58-151"><a href="#cb58-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-152"><a href="#cb58-152" aria-hidden="true" tabindex="-1"></a>$$grooming\ duration \sim reproductive\ condition + parity + (1|subject) + \epsilon$$</span>
<span id="cb58-153"><a href="#cb58-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-154"><a href="#cb58-154" aria-hidden="true" tabindex="-1"></a>Here, the 1 refers to the fact that we want to estimate an *intercept* and the pipe "\|" operator following the "1" signifies that we want to estimate a *different intercept for each subject*. Note that this generic formula still contains a general error term, $\epsilon$, to highlight that there will still be unexplained "error" variance after accounting for both fixed and random effects in the model.</span>
<span id="cb58-155"><a href="#cb58-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-156"><a href="#cb58-156" aria-hidden="true" tabindex="-1"></a>We can think of this formula as saying that we expect our dataset to include multiple observations of the response variable per subject, and these responses will depend, in part, on each subject's baseline level. This effectively accounts the nonindependence that stems from having multiple responses by the same subject.</span>
<span id="cb58-157"><a href="#cb58-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-158"><a href="#cb58-158" aria-hidden="true" tabindex="-1"></a>The {lme4} package in **R** is commonly used for mixed effects modeling, and the function <span class="in">`lmer()`</span> is the mixed model equivalent of the function <span class="in">`lm()`</span>. In the formula syntax for mixed effects models using the {lme4} package, fixed effects are included without parentheses while random effects are included in parentheses (the error, $\epsilon$, is understood and is not included explicitly).</span>
<span id="cb58-159"><a href="#cb58-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-160"><a href="#cb58-160" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** We could also use the package {nlme} for mixed effects modeling (which requires a slightly different formula syntax than that used here). That same package also allows us to do **nonlinear** mixed effects modeling, which we will not be talking about. It is important to note that {lme4} uses, by default, a slightly different parameter estimation algorithm than {nlme}. Unless otherwise specified, {lme4} uses "restricted maximum likelihood" (REML) rather than ordinary maximum likelihood estimation, which is what is used in {nlme}. In practice, these give very similar results. We will see below that when we want to compare different models using {lme4}, we will need to tell {lme4} to use ordinary maximum likelihood.</span></span>
<span id="cb58-161"><a href="#cb58-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-162"><a href="#cb58-162" aria-hidden="true" tabindex="-1"></a>The code block below implements this first "mixed effects" model:</span>
<span id="cb58-163"><a href="#cb58-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-166"><a href="#cb58-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-167"><a href="#cb58-167" aria-hidden="true" tabindex="-1"></a>lme <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-168"><a href="#cb58-168" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">|</span> subject))</span>
<span id="cb58-169"><a href="#cb58-169" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme)</span>
<span id="cb58-170"><a href="#cb58-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-171"><a href="#cb58-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-172"><a href="#cb58-172" aria-hidden="true" tabindex="-1"></a>Let's focus on the output for the random effects first. Have a look at the column standard deviation. The entry for *subject* shows us how much variability in grooming duration (apart from that explained by the fixed effects) is due to subject ID. The entry for *Residual* summarizes the remaining variability in grooming duration that is not due to *subject* or to our fixed effects. This is our $\epsilon$, the "random" deviations from the predicted values that are not due to either subject or our fixed effects.</span>
<span id="cb58-173"><a href="#cb58-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-174"><a href="#cb58-174" aria-hidden="true" tabindex="-1"></a>The fixed effects output mirrors the coefficient tables that we have seen previously in our linear models that have focused only on fixed effects. The coefficient "reproconditionPOP" is the $\beta$ coefficient (slope) for the categorical effect of reproductive condition. The positive sign for the coefficient means that grooming duration is GREATER by 20.293 units for POP than for NONPOP females. Then, there's a standard error associated with this slope, and a t value, which is simply the estimate divided by the standard error.</span>
<span id="cb58-175"><a href="#cb58-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-176"><a href="#cb58-176" aria-hidden="true" tabindex="-1"></a>The coefficient "parityP" is the $\beta$ coefficient for the categorical effect of parity. The grooming duration associated with being parous versus nulliparous is GREATER by 109.65 units.</span>
<span id="cb58-177"><a href="#cb58-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-178"><a href="#cb58-178" aria-hidden="true" tabindex="-1"></a>The INTERCEPT in this case is the grooming duration associated with being an average, nulliparous, NONPOP female. Like the <span class="in">`lm()`</span> function, the <span class="in">`lmer()`</span> took whatever factor level came first in the alphabet to be the reference level for each fixed effect variable.</span>
<span id="cb58-179"><a href="#cb58-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-180"><a href="#cb58-180" aria-hidden="true" tabindex="-1"></a>Let's also look at the coefficients coming out of the model.</span>
<span id="cb58-181"><a href="#cb58-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-184"><a href="#cb58-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-185"><a href="#cb58-185" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(lme)</span>
<span id="cb58-186"><a href="#cb58-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-187"><a href="#cb58-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-188"><a href="#cb58-188" aria-hidden="true" tabindex="-1"></a>We can see the separate intercepts, or "baseline" level of grooming received, associated with each female when they are (presumably) nulliparous and in a NONPOP reproductive condition.</span>
<span id="cb58-189"><a href="#cb58-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-190"><a href="#cb58-190" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** Not all females are, necessarily, ever seen in a particular parity or reproductive condition!</span></span>
<span id="cb58-191"><a href="#cb58-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-192"><a href="#cb58-192" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inference using LRTs {.unnumbered}</span></span>
<span id="cb58-193"><a href="#cb58-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-194"><a href="#cb58-194" aria-hidden="true" tabindex="-1"></a>In mixed effects models, it is not as straightforward as it is for standard linear models to determine p values associated with either overall models or individual coefficients. However, using **likelihood ratio tests**, which we previously used for comparing among generalized linear models, is one common approach. Likelihood is the probability of seeing the data we have actually collected *given* a particular model. The logic of the likelihood ratio test is to compare the likelihood of two models with each other, i.e., a model that includes the factor that we are interested in versus a reduced, nested model with that factor excluded.</span>
<span id="cb58-195"><a href="#cb58-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-196"><a href="#cb58-196" aria-hidden="true" tabindex="-1"></a>So... if we are interested in the effect of **reproductive condition** on grooming duration, we could compare a more complex model...</span>
<span id="cb58-197"><a href="#cb58-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-198"><a href="#cb58-198" aria-hidden="true" tabindex="-1"></a>$$grooming\ duration \sim reproductive\ condition + parity + (1|subject) + \epsilon$$</span>
<span id="cb58-199"><a href="#cb58-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-200"><a href="#cb58-200" aria-hidden="true" tabindex="-1"></a>to a nested, less complex model...</span>
<span id="cb58-201"><a href="#cb58-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-202"><a href="#cb58-202" aria-hidden="true" tabindex="-1"></a>$$grooming\ duration \sim parity + (1|subject) + \epsilon$$</span>
<span id="cb58-203"><a href="#cb58-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-204"><a href="#cb58-204" aria-hidden="true" tabindex="-1"></a>In ***R***, we would do this as follows:</span>
<span id="cb58-205"><a href="#cb58-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-208"><a href="#cb58-208" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-209"><a href="#cb58-209" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-210"><a href="#cb58-210" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-211"><a href="#cb58-211" aria-hidden="true" tabindex="-1"></a><span class="co"># note the additional `REML=` argument</span></span>
<span id="cb58-212"><a href="#cb58-212" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full)</span>
<span id="cb58-213"><a href="#cb58-213" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> parity <span class="sc">+</span></span>
<span id="cb58-214"><a href="#cb58-214" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>) </span>
<span id="cb58-215"><a href="#cb58-215" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced)</span>
<span id="cb58-216"><a href="#cb58-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-217"><a href="#cb58-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-218"><a href="#cb58-218" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** Here, we added the argument </span><span class="in">`REML=FALSE`</span><span class="at"> to the </span><span class="in">`lmer()`</span><span class="at"> function. This is necessary to do when we want to compare models using the likelihood ratio test. Basically, REML uses a different algorithm to determine likelihood values than ordinary likelihood, and, if we want to use these likelihoods to execute an LRT, we need to use ordinary likelihood. See </span><span class="co">[</span><span class="ot">this site</span><span class="co">](http://users.stat.umn.edu/~gary/classes/5303/handouts/REML.pdf)</span><span class="at"> for a more complete explanation of this issue.</span></span>
<span id="cb58-219"><a href="#cb58-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-220"><a href="#cb58-220" aria-hidden="true" tabindex="-1"></a>We then perform the likelihood ratio test using the <span class="in">`anova()`</span> function or the <span class="in">`lrtest()`</span> function from {lmtest}.</span>
<span id="cb58-221"><a href="#cb58-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-224"><a href="#cb58-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-225"><a href="#cb58-225" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb58-226"><a href="#cb58-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb58-227"><a href="#cb58-227" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb58-228"><a href="#cb58-228" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb58-229"><a href="#cb58-229" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(reduced, full)</span>
<span id="cb58-230"><a href="#cb58-230" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>lmtest)</span>
<span id="cb58-231"><a href="#cb58-231" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-232"><a href="#cb58-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-233"><a href="#cb58-233" aria-hidden="true" tabindex="-1"></a>These results tell us that the model containing both **reproductive condition** and **parity** as *fixed* effects fits the data better than a model lacking **reproductive condition** and containing only **parity** as a *fixed* effect, while accounting for **subject** as a *random* effect.</span>
<span id="cb58-234"><a href="#cb58-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-235"><a href="#cb58-235" aria-hidden="true" tabindex="-1"></a><span class="fu">### CHALLENGE {.unnumbered}</span></span>
<span id="cb58-236"><a href="#cb58-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-237"><a href="#cb58-237" aria-hidden="true" tabindex="-1"></a>Now, compare a model containing **reproductive condition** and **parity** to one containing just **reproductive condition**.</span>
<span id="cb58-238"><a href="#cb58-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-241"><a href="#cb58-241" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-242"><a href="#cb58-242" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-243"><a href="#cb58-243" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-244"><a href="#cb58-244" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span><span class="sc">|</span>subject), <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb58-245"><a href="#cb58-245" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data=</span>d, duration<span class="sc">~</span>reprocondition <span class="sc">+</span></span>
<span id="cb58-246"><a href="#cb58-246" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span><span class="sc">|</span>subject), <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb58-247"><a href="#cb58-247" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb58-248"><a href="#cb58-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-249"><a href="#cb58-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-250"><a href="#cb58-250" aria-hidden="true" tabindex="-1"></a>Based on this result, including **parity** as well as **reproductive condition** as fixed effects also significantly improves the fit of our model.</span>
<span id="cb58-251"><a href="#cb58-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-252"><a href="#cb58-252" aria-hidden="true" tabindex="-1"></a><span class="fu">### CHALLENGE {.unnumbered}</span></span>
<span id="cb58-253"><a href="#cb58-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-254"><a href="#cb58-254" aria-hidden="true" tabindex="-1"></a>Construct a model that includes an interaction of **reproductive condition** and **parity** and compare it to a model without the interaction term. Is the interaction of these two fixed effects significant?</span>
<span id="cb58-255"><a href="#cb58-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-258"><a href="#cb58-258" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-259"><a href="#cb58-259" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb58-260"><a href="#cb58-260" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">*</span> parity <span class="sc">+</span></span>
<span id="cb58-261"><a href="#cb58-261" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-262"><a href="#cb58-262" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-263"><a href="#cb58-263" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb58-264"><a href="#cb58-264" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb58-265"><a href="#cb58-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-266"><a href="#cb58-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-267"><a href="#cb58-267" aria-hidden="true" tabindex="-1"></a>In this case, adding the interaction of **reproductive condition** and **parity** does not significantly improve the explanatory power of the model.</span>
<span id="cb58-268"><a href="#cb58-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-269"><a href="#cb58-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## Random Slope Models</span></span>
<span id="cb58-270"><a href="#cb58-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-271"><a href="#cb58-271" aria-hidden="true" tabindex="-1"></a>In the exercise above, we included only estimation of a separate INTERCEPT for each female and presumed that the same relationships (SLOPES) between grooming duration and reproductive condition + parity obtained for all females. But we can also allow that relationship to vary from subject to subject. We would indicate this model in formula notation as follows:</span>
<span id="cb58-272"><a href="#cb58-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-273"><a href="#cb58-273" aria-hidden="true" tabindex="-1"></a>$$grooming\ duration \sim reproductive\ condition + parity\ +$$ $$(1 + reproductive\ condition|subject) + (1 + parity|subject) + \epsilon$$</span>
<span id="cb58-274"><a href="#cb58-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-277"><a href="#cb58-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-278"><a href="#cb58-278" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb58-279"><a href="#cb58-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb58-280"><a href="#cb58-280" aria-hidden="true" tabindex="-1"></a>lme <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-281"><a href="#cb58-281" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject),</span>
<span id="cb58-282"><a href="#cb58-282" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-283"><a href="#cb58-283" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme)</span>
<span id="cb58-284"><a href="#cb58-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-285"><a href="#cb58-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-286"><a href="#cb58-286" aria-hidden="true" tabindex="-1"></a>Here, we have changed the random effects, which now look a little more complicated. The notation "(1 + reprocondition \| subject)" tells the model to estimate differing baseline levels of grooming duration (the intercept, represented by 1) as well as differing responses to the main factor in question, which is reproductive condition in this case. We do the same for parity.</span>
<span id="cb58-287"><a href="#cb58-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-288"><a href="#cb58-288" aria-hidden="true" tabindex="-1"></a>Looking at the coefficients of the new model, we see the effects. Each female now has a different intercept **and** a different coefficient for the slopes of grooming duration as a function of both reproductive condition and parity.</span>
<span id="cb58-289"><a href="#cb58-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-292"><a href="#cb58-292" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-293"><a href="#cb58-293" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(lme)</span>
<span id="cb58-294"><a href="#cb58-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-295"><a href="#cb58-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-296"><a href="#cb58-296" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inference using LRTs {.unnumbered}</span></span>
<span id="cb58-297"><a href="#cb58-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-298"><a href="#cb58-298" aria-hidden="true" tabindex="-1"></a>To then get p values associated with each of the fixed factors, we can use likelihood ratio tests...</span>
<span id="cb58-299"><a href="#cb58-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-302"><a href="#cb58-302" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-303"><a href="#cb58-303" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb58-304"><a href="#cb58-304" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb58-305"><a href="#cb58-305" aria-hidden="true" tabindex="-1"></a><span class="co"># random factors only</span></span>
<span id="cb58-306"><a href="#cb58-306" aria-hidden="true" tabindex="-1"></a>null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span></span>
<span id="cb58-307"><a href="#cb58-307" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject), <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-308"><a href="#cb58-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-309"><a href="#cb58-309" aria-hidden="true" tabindex="-1"></a><span class="co"># full model with both fixed effects</span></span>
<span id="cb58-310"><a href="#cb58-310" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span> parity <span class="sc">+</span></span>
<span id="cb58-311"><a href="#cb58-311" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject),</span>
<span id="cb58-312"><a href="#cb58-312" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-313"><a href="#cb58-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-314"><a href="#cb58-314" aria-hidden="true" tabindex="-1"></a><span class="co"># model without reproductive condition as a fixed effect</span></span>
<span id="cb58-315"><a href="#cb58-315" aria-hidden="true" tabindex="-1"></a>minusRC <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> parity <span class="sc">+</span></span>
<span id="cb58-316"><a href="#cb58-316" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject),</span>
<span id="cb58-317"><a href="#cb58-317" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-318"><a href="#cb58-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-319"><a href="#cb58-319" aria-hidden="true" tabindex="-1"></a><span class="co"># model without parity as a fixed effect</span></span>
<span id="cb58-320"><a href="#cb58-320" aria-hidden="true" tabindex="-1"></a>minusP <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">data =</span> d, duration <span class="sc">~</span> reprocondition <span class="sc">+</span></span>
<span id="cb58-321"><a href="#cb58-321" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">+</span> reprocondition <span class="sc">|</span> subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> parity <span class="sc">|</span> subject),</span>
<span id="cb58-322"><a href="#cb58-322" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb58-323"><a href="#cb58-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-324"><a href="#cb58-324" aria-hidden="true" tabindex="-1"></a><span class="co"># p value for reproductive condition as a fixed effect</span></span>
<span id="cb58-325"><a href="#cb58-325" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(minusRC, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb58-326"><a href="#cb58-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-327"><a href="#cb58-327" aria-hidden="true" tabindex="-1"></a><span class="co"># p value for parity as a fixed effect</span></span>
<span id="cb58-328"><a href="#cb58-328" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(minusP, full, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb58-329"><a href="#cb58-329" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-330"><a href="#cb58-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-331"><a href="#cb58-331" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inference using AIC {.unnumbered}</span></span>
<span id="cb58-332"><a href="#cb58-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-333"><a href="#cb58-333" aria-hidden="true" tabindex="-1"></a>For a long time, the appropriateness of our mixed models was assessed as above - i.e., by evaluating the significance of each fixed effect using LRTs. As information theoretic approaches have become more popular, it is increasingly common to assess model fit by comparing the AIC values of different models, acknowledging the caveat that AIC can only tell us about the *relative* fit of alternative models, but not whether a particular model is a good fit, overall. Recall that AIC values are a way of inverting and scaling model log-likelihoods that penalizes models with greater numbers of parameters.</span>
<span id="cb58-334"><a href="#cb58-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-335"><a href="#cb58-335" aria-hidden="true" tabindex="-1"></a>The <span class="in">`aictab()`</span> function from {AICcmodavg} neatly prints out tables with AIC, Delta AIC, and log-likelihood values, along with AIC "weights".</span>
<span id="cb58-336"><a href="#cb58-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-339"><a href="#cb58-339" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-340"><a href="#cb58-340" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb58-341"><a href="#cb58-341" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb58-342"><a href="#cb58-342" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span>
<span id="cb58-343"><a href="#cb58-343" aria-hidden="true" tabindex="-1"></a>(aic_table <span class="ot">&lt;-</span> <span class="fu">aictab</span>( <span class="fu">list</span>(full, minusRC, minusP, null),</span>
<span id="cb58-344"><a href="#cb58-344" aria-hidden="true" tabindex="-1"></a>  <span class="at">modnames =</span> <span class="fu">c</span>(<span class="st">"full"</span>, <span class="st">"minusRC"</span>, <span class="st">"minusP"</span>, <span class="st">"null"</span>)))</span>
<span id="cb58-345"><a href="#cb58-345" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>AICcmodavg)</span>
<span id="cb58-346"><a href="#cb58-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-347"><a href="#cb58-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-348"><a href="#cb58-348" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** Here we are printing out AICc values, rather than AIC values. AICc is simply a version of AIC with a correction added for small sample sizes. To print the uncorrected AIC values, which appear in the </span><span class="in">`anova()`</span><span class="at"> LRT output, we can add the argument </span><span class="in">`second.ord=TRUE`</span><span class="at"> to the </span><span class="in">`aictab()`</span><span class="at"> function.</span></span>
<span id="cb58-349"><a href="#cb58-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-350"><a href="#cb58-350" aria-hidden="true" tabindex="-1"></a>$$AIC_c = AIC + \frac{2K^2 + 2K}{n-K-1}$$</span>
<span id="cb58-351"><a href="#cb58-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-352"><a href="#cb58-352" aria-hidden="true" tabindex="-1"></a>where $K$ is the number of parameters and $n$ is the sample size.</span>
<span id="cb58-353"><a href="#cb58-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-354"><a href="#cb58-354" aria-hidden="true" tabindex="-1"></a>In the table, for each model, $K$ is the number of model parameters, the $Delta\  AICc$ value is the difference between that model's AICc and the best model's AICc (again, here, that is the full model), and the $AICc\ weight$ is the relative likelihood of that model. <span class="co">[</span><span class="ot">The weights for a particular set of models sums to 1, with each weight equal to the model's likelihood divided by the summed likelihoods across all models.</span><span class="co">]</span></span>
<span id="cb58-355"><a href="#cb58-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-356"><a href="#cb58-356" aria-hidden="true" tabindex="-1"></a>Where the best model has a very high Akaike weight, e.g., <span class="sc">\&gt;</span>0.9, it is reasonable to base inferences about the included variables on that single most parsimonious model, but when several models rank highly (e.g., several models have Delta AICc values <span class="sc">\&lt;</span>2 to 4), it is common to model-average effect sizes for the variables that have the most support across that set of models. That is, "model averaging" means making inferences based on a **set** of candidate models, instead of on a single "best" model.</span>
<span id="cb58-357"><a href="#cb58-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-358"><a href="#cb58-358" aria-hidden="true" tabindex="-1"></a>Here, note that the full model containing both *reproductive condition* and *parity* has the highest likelihood (the least negative log-likelihood value) and a much lower AICc than any of the less complex alternative models tested. It also has a very high Akaike weight (0.91).</span>
<span id="cb58-359"><a href="#cb58-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-360"><a href="#cb58-360" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **NOTE:** When running a number of the above models and/or in doing the likelihood ratio tests, we saw a significant result but we also got either a warning that our null models "failed to converge" or we saw a warning about a "boundary (singular) fit". Both of these warning are due to having a LOT of parameters we are trying to estimate relative to the number of observations we have. Dealing with lack of convergence in fitting maximum likelihood models is beyond what we can cover here, but I encourage you to explore that on your own!</span></span>
<span id="cb58-361"><a href="#cb58-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-362"><a href="#cb58-362" aria-hidden="true" tabindex="-1"></a><span class="fu">### Other Methods for Assessing Fit {.unnumbered}</span></span>
<span id="cb58-363"><a href="#cb58-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-364"><a href="#cb58-364" aria-hidden="true" tabindex="-1"></a>Using likelihood ratio tests and AIC values for evaluating and expressing how well a particular model fits a dataset both have some critical limitations:</span>
<span id="cb58-365"><a href="#cb58-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-366"><a href="#cb58-366" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>While AIC provides an estimate of the *relative* fit of various models, it does not say anything about the absolute fit</span>
<span id="cb58-367"><a href="#cb58-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>AIC does not address the amount of variance in a response variable explained by a model</span>
<span id="cb58-368"><a href="#cb58-368" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>AIC is not comparable across datasets, and so fit is not generalizable</span>
<span id="cb58-369"><a href="#cb58-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-370"><a href="#cb58-370" aria-hidden="true" tabindex="-1"></a>Nakagawa &amp; Schielzeth (2013) and Nakagawa et al. (2017) have published a simple and effective method for calculating a type of *pseudo-*$R^2$ (or coefficient of determination) value for generalized linear mixed models, and because linear mixed models are a specific type of GLMM, this method can be used with LMMs as well.</span>
<span id="cb58-371"><a href="#cb58-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-372"><a href="#cb58-372" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; See:</span></span>
<span id="cb58-373"><a href="#cb58-373" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb58-374"><a href="#cb58-374" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; - Nakagawa, S., &amp; Schielzeth, H. (2013). A general and simple method for obtaining R2 from generalized linear mixed-effects models. *Methods in Ecology and Evolution*, 4, 133--142.</span></span>
<span id="cb58-375"><a href="#cb58-375" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb58-376"><a href="#cb58-376" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; - Nakagawa, S., Johnson, P. C. D., &amp; Schielzeth, H. (2017). The coefficient of determination R2 and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded. *Journal of the Royal Society Interface*, 14, article 20170213.</span></span>
<span id="cb58-377"><a href="#cb58-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-378"><a href="#cb58-378" aria-hidden="true" tabindex="-1"></a>In these papers, two measures are proposed for characterizing the amount of "variance explained" in for mixed effects models:</span>
<span id="cb58-379"><a href="#cb58-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-380"><a href="#cb58-380" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$Marginal\ R2GLMM(m)^2$ is the amount of variance explained on the latent (or link) scale rather than the original scale. We can interpret this as a measure of the variance explained by only the fixed effects.</span>
<span id="cb58-381"><a href="#cb58-381" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$Conditional\ R2GLMM(c)^2$ is the amount of variance explained by both fixed and random effects, i.e., by the entire model.</span>
<span id="cb58-382"><a href="#cb58-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-383"><a href="#cb58-383" aria-hidden="true" tabindex="-1"></a>There is an easy way to calculate these two R2GLMM values in ***R*** using the <span class="in">`r.squaredGLMM()`</span> function in the package {MuMIn}.</span>
<span id="cb58-384"><a href="#cb58-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-385"><a href="#cb58-385" aria-hidden="true" tabindex="-1"></a><span class="fu">### CHALLENGE {.unnumbered}</span></span>
<span id="cb58-386"><a href="#cb58-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-387"><a href="#cb58-387" aria-hidden="true" tabindex="-1"></a>Compare the full, the two reduced, and the null mixed effects models from our random slope exercise using an information theoretic approach. Is the best model (full) the one that explains the greatest amount of variance in the dataset? In the full model, how much more of the total variance is explained by the random effects than by the fixed effects alone?</span>
<span id="cb58-388"><a href="#cb58-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-391"><a href="#cb58-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-392"><a href="#cb58-392" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb58-393"><a href="#cb58-393" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb58-394"><a href="#cb58-394" aria-hidden="true" tabindex="-1"></a>aic_table <span class="co"># re-print the AIC table</span></span>
<span id="cb58-395"><a href="#cb58-395" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span>
<span id="cb58-396"><a href="#cb58-396" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(full)</span>
<span id="cb58-397"><a href="#cb58-397" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(minusRC)</span>
<span id="cb58-398"><a href="#cb58-398" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(minusP)</span>
<span id="cb58-399"><a href="#cb58-399" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(null)</span>
<span id="cb58-400"><a href="#cb58-400" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>MuMIn)</span>
<span id="cb58-401"><a href="#cb58-401" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-402"><a href="#cb58-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-403"><a href="#cb58-403" aria-hidden="true" tabindex="-1"></a><span class="fu">## Generalized LMMs</span></span>
<span id="cb58-404"><a href="#cb58-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-405"><a href="#cb58-405" aria-hidden="true" tabindex="-1"></a>Just as we extended our standard linear modeling approach to include non-normally distributed response variables/error structures, so too can we extend our mixed effects modeling to such situations. This is referred to as **generalized linear mixed modeling, or GLMM**. There are several ***R*** packages we can use to do this under either a maximum likelihood (e.g., {lme4}, {glmmML}, the no-longer-maintained {glmmboot}) or Bayesian (e.g., {MCMCglmm}, {glmmTMB}, {brms}) framework. The methods for generating maximum likelihood and Bayesian parameter estimates under GLMMs are more complicated, but conceptually, the process is an extension of what we have talked about already. Below, we explore such a scenario.</span>
<span id="cb58-406"><a href="#cb58-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-407"><a href="#cb58-407" aria-hidden="true" tabindex="-1"></a><span class="fu">### CHALLENGE {.unnumbered}</span></span>
<span id="cb58-408"><a href="#cb58-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-409"><a href="#cb58-409" aria-hidden="true" tabindex="-1"></a>Boden-Parry et al. (2020) studied the effect of food type and abundance on the begging and food sharing behavior of otters in captivity.</span>
<span id="cb58-410"><a href="#cb58-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-413"><a href="#cb58-413" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-414"><a href="#cb58-414" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Bowden-ParryOtterdata.csv"</span></span>
<span id="cb58-415"><a href="#cb58-415" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-416"><a href="#cb58-416" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span>
<span id="cb58-417"><a href="#cb58-417" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmML)</span>
<span id="cb58-418"><a href="#cb58-418" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-419"><a href="#cb58-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-420"><a href="#cb58-420" aria-hidden="true" tabindex="-1"></a>Bowden-Parry, M.; Postma, E.; and Boogert, N.J. (2020). Effects of food type and abundance on begging and sharing in Asian small-clawed otters (*Aonyx cinereus*). *PeerJ* 8: e10369.</span>
<span id="cb58-421"><a href="#cb58-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-424"><a href="#cb58-424" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-425"><a href="#cb58-425" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb58-426"><a href="#cb58-426" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>glmmML)</span>
<span id="cb58-427"><a href="#cb58-427" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>lme4)</span>
<span id="cb58-428"><a href="#cb58-428" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(package<span class="sc">:</span>tidyverse)</span>
<span id="cb58-429"><a href="#cb58-429" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-430"><a href="#cb58-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-431"><a href="#cb58-431" aria-hidden="true" tabindex="-1"></a>&lt;hr&gt;</span>
<span id="cb58-432"><a href="#cb58-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-433"><a href="#cb58-433" aria-hidden="true" tabindex="-1"></a><span class="fu">## Concept Review {.unnumbered}</span></span>
<span id="cb58-434"><a href="#cb58-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-435"><a href="#cb58-435" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>"Mixed" modeling extends general and generalized linear modeling to consider cases where we have additional "random" factors that are another source of possible variation in our response variable</span>
<span id="cb58-436"><a href="#cb58-436" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The approach allows us to estimate either different intercepts or different slopes *and* intercepts for each level of the random factor</span>
<span id="cb58-437"><a href="#cb58-437" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>As in generalized linear modeling, likelihood ratio tests and information criteria approaches can be used to compare the explanatory power of different models</span>
<span id="cb58-438"><a href="#cb58-438" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Though we do not address it in this class, regression modeling can be extended further to consider NONLINEAR relationships among predictor variables</span>
<span id="cb58-439"><a href="#cb58-439" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>The ***R*** packages {lme4} and {nlme} provide functions for performing for "nonlinear mixed effects modeling"</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>